name: stock_tracker
description: Multi-user stock tracking Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: 0.6.2+1
  cloud_firestore: 0.8.2+3
  http:
  cloud_firestore:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
